### ISSUE TITLE
Update annotation workflow to sync with JGI annotation version 5.1

### ISSUE THREAD

**Issue by aclum** [microbiomedata/mg_annotation#13]
JGI is on annotation version 5.1.*, NMDC is still on version 5.0. Update workflow to be up to date with JGI.

**Comment by aclum** [comment]
This is a retroactive ticket. Work was done on this November 2022 - January 2023 under the 5.1_sync branch. Work was merged back to the werkflow branch. cc @ssarrafan

**Comment by ssarrafan** [comment]
Since it continued through January I will add this to the sprint.
