### ISSUE TITLE
Update to new version of img-nr database

### ISSUE THREAD

**Issue by aclum** [microbiomedata/mg_annotation#16]
[Deliverable](https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit#gid=417989680) this task is associated with

1

RACI

Responsible: @Michal-Babins 
Accountable: @aclum
Consulted: @hubin-keio 
Informed: 

Describe the task?

- [x] Update the version of the img-nr database for the annotation pipeline. This will be provided by Marcel and should be copied to /global/cfs/cdirs/m3408/refdata/img/IMG-NR/YYYYMMDD
- [x] update functional-annotation.wdl to use the new version, input variables are variables are 
- [x] update to lastal 1456
```
ko_ec_img_nr_db
ko_ec_md5_mapping
ko_ec_taxon_to_phylo_mapping

```
Criteria for completion

A test annotation workflow run completes successfully and the imgap_version file has a img-nr database version has a year matching 2023

Completion Date (Goal)

July 7
Target Sprint Start & End Dates

Start: July 3
End: July 14
Tag Blocker/Contingent upon issues
Dependent on new database version release from @mhuntemann

**Comment by aclum** [comment]
@Michal-Babins  I've copied over the new version of the img-nr database to /global/cfs/cdirs/m3408/refdata/img/IMG-NR/20230629/ Marcel said it is 45% larger than the previous version and he is seeing longer run times for lastal.
Please update the wdl to use this new version.

**Comment by ssarrafan** [comment]
@aclum @Michal-Babins what is the status of this issue?  I don't see any updates this sprint.  Still active? Or label with backlog?

**Comment by aclum** [comment]
This was completed in in sprint 15. Workflow runs in July and August use the updated version of lastal and the IMG-NR database.
