### ISSUE TITLE
update CRT to pull form public repo 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/mg_annotation#17]
The current docker container pulls a version of CRT from a nersc ftp site, Marcel has made this repo public so we should pull and build the code from the public repo. CRT version CRT-CLI_v1.8.4 
repo: https://code.jgi.doe.gov/img/img-pipelines/crt-cli-imgap-version

**Comment by Michal-Babins** [comment]
@aclum , I pushed to updated Dockerfile to master, however to not have microbiomedata dockerhub account to push the image

**Comment by aclum** [comment]
@Michal-Babins  I just resent the invitation to join the dockerhub microbiomedata org

**Comment by Michal-Babins** [comment]
@aclum, when I try to push to the repo, I get:

`denied: requested access to the resource is denied`

Are there still extra permissions that need to be granted?

**Comment by aclum** [comment]
New docker container was pushed
