### ISSUE TITLE
add scaffold lineage file to wdl outputs

### ISSUE THREAD

**Issue by aclum** [microbiomedata/mg_annotation#19]
Marcel next week should be providing an updated version that outputs a lineage file. The wdl workflow should be updated to have this as an output and the runtime automation should make a data object for this file. A file enum,Lineage sdb, has been made already. 

Blocked on updates from Marcel and runtime API being updated to schema version 7.7

**Comment by aclum** [comment]
@Michal-Babins  This version is available in this branch 
https://code.jgi.doe.gov/img/img-pipelines/img-annotation-pipeline/-/tree/scaffold-lineage

**Comment by Michal-Babins** [comment]
@aclum updated the docker image sha

**Comment by ssarrafan** [comment]
@aclum @Michal-Babins what's the status of this issue?  any updates?

**Comment by Michal-Babins** [comment]
Scaffold lineage file has been added with the mg_annotation version 5.2.0. Scaffold lineage tsv accepted now as input to mags.
