### ISSUE TITLE
update-v1

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/mg_annotation#23]
Update WDL's to use Version 1.0

**Comment by aclum** [comment]
Mark and I have been working on this. The updated wdl validates against the 1.0 spec.

**Comment by mflynn-lanl** [comment]
ReadsQC, ReadbasedAnalysis and metaAnnotation have all been done by Alicia and I. Kaitlyn Li has done metaAssembly as a part of adding long reads

**Comment by ssarrafan** [comment]
Based on the last 2 comments I'm closing this issue.  @aclum @mflynn-lanl re-open if necessary and add to the next sprint.

**Comment by aclum** [comment]
@mflynn-lanl  we need releases for these, then nmdc-automation needs to be updated to use these (this can be a separate linked ticket) but at a minimum we do need these merged to main and a tagged release. Cc @Michal-Babins and @mbthornton-lbl for coordination.

**Comment by aclum** [comment]
@mflynn-lanl do you have time to do the merges and releases this sprint?

**Comment by aclum** [comment]
backlog until nmdc edge sync is resolved. Target for sprint starting with week of Dec 18

**Comment by kaijli** [comment]
successful run of v1.0 on https://github.com/microbiomedata/mg_annotation/tree/23-update-v1
jaws id 79771

**Comment by kaijli** [comment]
PR at https://github.com/microbiomedata/mg_annotation/pull/29

**Comment by ssarrafan** [comment]
Will move to next sprint per the PR comment 3 days ago
@kaijli @aclum

**Comment by kaijli** [comment]
merged PR https://github.com/microbiomedata/mg_annotation/pull/29 and bumped version https://github.com/microbiomedata/mg_annotation/releases/tag/v1.1.1
