### ISSUE TITLE
add support for Contig Mapping File 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/mg_annotation#24]
There are a few things we need to confirm are working properly so we can support NMDC workflows that start with an input assembly file. That is, workflows that start with a contigs file, instead of reads. 
In this case we need to 
- [ ] execute pre_qc_execute from a customized inputs.json generated by workflow automation
- [ ] make sure that mapping file is output from the workflow in the wdl task and workflow outputs block 
- [ ] make sure the output renamed contig file is the input to the other wdl structural_annotation tasks.

see related task on the automation side https://github.com/microbiomedata/nmdc_automation/issues/35

cc @mhuntemann @scanon

**Comment by aclum** [comment]
@hubin-keio  is there someone else on the LANL side that can work on this?

**Comment by aclum** [comment]
If you need to look at the original code that our pre_qc task comes from it is here
https://code.jgi.doe.gov/img/img-pipelines/img-annotation-pipeline/-/tree/main/bin/qc/pre-annotation?ref_type=heads

**Comment by aclum** [comment]
This is required for rerunning annotation post re-iding (if assemblies came from JGI), 16 JGI 1000 soil projects and 87 JGI NEON projects.

**Comment by ssarrafan** [comment]
@mbthornton-lbl will be continuing to work on this in the next sprint per Slack message. Moving over.

**Comment by kaijli** [comment]
Currently testing addition of map file task to master branch of mg_annotation [(new branch called mapping)](https://github.com/microbiomedata/mg_annotation/tree/mapping). Tried adding it to wdl v 1.0 branch but ran into gm_license issues [(branched called map_file)](https://github.com/microbiomedata/mg_annotation/tree/map_file).

**Comment by kaijli** [comment]
Branch is ready for merge, [pull request created](https://github.com/microbiomedata/mg_annotation/pull/27), test results sent to @aclum

**Comment by aclum** [comment]
@kaijli  is there an update here? Based on the last discussion the annotation identifiers should be used.

**Comment by aclum** [comment]
Per @kaijli in testing.

**Comment by ssarrafan** [comment]
Moving to next sprint to complete testing

**Comment by kaijli** [comment]
https://github.com/microbiomedata/mg_annotation/pull/28
merged with master branch
