### ISSUE TITLE
update product mapping files

### ISSUE THREAD

**Issue by aclum** [microbiomedata/mg_annotation#25]
We missed updating to the new product mapping tables when we updated to img annotation version 5.2. 
Update the workflow to use /global/cfs/cdirs/m3408/refdata/img/Product_Name_Mappings/20230814

This is what Marcel is now using.

cc @hubin-keio

**Comment by aclum** [comment]
@kaijli @Michal-Babins  is there an update here? this needs to be updated before we start running workflows again.

**Comment by ssarrafan** [comment]
@hubin-keio brought this up at the sync today.  @Michal-Babins @hubin-keio @aclum who should be part of this discussion?

**Comment by aclum** [comment]
Discussing the general issue of staying in sync with JGI is separate than fixing this specific issue. We can and should move forward with this fix so we can resume the workflows.

**Comment by chienchi** [comment]
The code in WDL use the `latest` symlink directory. So, I think we only need to update the `refdata/img/Product_Name_Mappings/lastest` symlink to point to `20230814`, right? The workflow WDL itself doesn't need update and make new release.

![image](https://github.com/microbiomedata/mg_annotation/assets/737589/ee0083d7-3196-47e3-8d18-9de8edf17861)

![image](https://github.com/microbiomedata/mg_annotation/assets/737589/aae5a38c-185a-4d8e-9296-1b5ded46f4f8)

**Comment by aclum** [comment]
I think that is bad practice and part of the reason why we didn't catch that these hadn't been updated in the first place.

**Comment by chienchi** [comment]
I see. We should update the wdl and use the correct path and make a new release.

**Comment by ssarrafan** [comment]
I moved this to the next sprint. @aclum is this required for GSP?  
FYI @chienchi @kaijli

**Comment by aclum** [comment]
yes b/c I'd like these fixed before we continue workflow processing.
