### ISSUE TITLE
Workflows - Test large data sets for workflows (mg_annotation)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/mg_annotation#4]
create a large test data set with expected outcome if workflow run is successful

link test results to this issue

**Comment by hubin-keio** [comment]
Will be tested at SDSC once the system (Cromwell etc.) is set up. Likely to get started near the last week of the Sprint.

**Comment by ssarrafan** [comment]
Moving to June sprint per @hubin-keio

**Comment by hubin-keio** [comment]
Test run succeed in command line. However, one JSON file was not generated from the version of WDL file used in EDGE NMDC. We'll need to sync the WDLs and Docker images of this workflows in next Sprint.

**Comment by ssarrafan** [comment]
Closing per Bin's note that this is done.  @hubin-keio let me know if we need a new issue for July to sync the WDLs and Docker images.
