### ISSUE TITLE
copy output files

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/mg_annotation#6]
The edge-nmdc website needs to display the output files for the annotation workflow. Currently, the output files for the mg-annotation workflow remain within the cromwell-execution directory after each task is completed. A task is needed to copy files from the cromwell-execution directory to a directory in `edge_app/nmdc-edge/projects`. This includes adding `outdir` as an optional input to the wdl and inputs.json files

**Comment by mflynn-lanl** [comment]
I will add a boolean `copy_outputs` that defaults to false so existing deployments of the workflow won't break.

**Comment by aclum** [comment]
@mflynn-lanl can this issue be deprecated in favor of plans to use the jaws API to fetch the data?  Being able to have the WDLs run across computing sites is in conflict with specifying an final output directory within the workflow since where the compute is done and where edge needs the files to display them may be different.

**Comment by mflynn-lanl** [comment]
Yes, that’s fine

From: aclum ***@***.***>
Reply-To: microbiomedata/mg_annotation ***@***.***>
Date: Monday, January 23, 2023 at 12:08 PM
To: microbiomedata/mg_annotation ***@***.***>
Cc: "Flynn, Mark C" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [microbiomedata/mg_annotation] copy output files (#6)


@mflynn-lanl<https://urldefense.com/v3/__https:/github.com/mflynn-lanl__;!!Bt8fGhp8LhKGRg!Dtwd9RqeL2nQqaS-PQh2uyaqDw9FiXLZI47KzFRlVKjRnYMMtrczygsYyWRb7SQ673C3Bc5E0u42OMkyJK824P9R$> can this issue be deprecated in favor of plans to use the jaws API to fetch the data? Being able to have the WDLs run across computing sites is in conflict with specifying an final output directory within the workflow since where the compute is done and where edge needs the files to display them may be different.
