### ISSUE TITLE
Analyze and resolve issue with missing annotation outputs for IMG

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/mg_annotation#8]

**Comment by ssarrafan** [comment]
@Michal-Babins are you still working on this?  I will move it to March sprint but let me know if it's not something you're actively working on.

**Comment by Michal-Babins** [comment]
@ssarrafan it mostly resolved but not implemented in the main workflow yet, so yeah can move to March.

**Comment by ssarrafan** [comment]
> @ssarrafan it mostly resolved but not implemented in the main workflow yet, so yeah can move to March.

Hi @Michal-Babins can this one be closed?  or should it continue to April?

**Comment by ssarrafan** [comment]
I'm moving to April. @Michal-Babins if you can close this that would be great.

**Comment by ssarrafan** [comment]
@Michal-Babins do you have any updates on this issue?  I am trying to close out the sprint on time since I'll be off next week.  Thanks for your help.

**Comment by ssarrafan** [comment]
@Michal-Babins I will remove this from the sprint and add the backlog label.  If you plan to work on this in May let me know and/or add to the May sprint board.

**Comment by aclum** [comment]
It would be nice to get this addressed once the workflow automation testing is finished. The merge_outputs task now has a more comprehensive list of files but that needs to get propagated to finish_ano along with the version info file from the make_info_file task.

**Comment by aclum** [comment]
IMG has been importing our NEON annotations so I believe this is resolved. I will close for now and this can be reopened if there were other projects that IMG needs to ingest. cc @ssarrafan
